### ISSUE TITLE
WKD

### ISSUE THREAD

**Issue by mmso** [ProtonMail/proton-contacts#134]
If you click on the settings button of an email of one of your contacts:
![image](https://user-images.githubusercontent.com/33841139/65580210-82341900-df79-11e9-8f33-789fc3939260.png)
a modal is displayed where you can set the PGP settings for communication with that email address.

Currently, in this modal we only display public keys (that you can decide to trust or not using Address Verification) for internal protonmail users. The idea with the Web Key Directory (WKD) is that public keys will also be available for certain external users. The API is already providing such keys, so the idea is to detect those users and display their keys retrieved from the WKD in this modal

**Comment by econdepe** [comment]
I have two questions regarding the logic/UX of this modal, which looks unclear to me in the new v4 version. First one goes here:

If I open the modal for an internal user, I expect to see pubic keys and the possibility of trusting them. That is true, but I find the alerts regarding Address Verification confusing.

![image](https://user-images.githubusercontent.com/33841139/65581149-4306c780-df7b-11e9-9383-5d875dedd598.png)

As seen in the picture, the blue alert tells you:

> To use Address Verification, you must trust one or more available public keys, including the primary key for this address. This prevents the encrypted keys from being faked.

The corresponding alert in v3 was slightly different:

> To use Address Verification, you must enable Trusted Keys and trust one or more available public keys, including the primary key for this address. This prevents the encryption keys from being faked

The difference comes from the fact that in v3 there used to be a button for activating "Trusted Keys". This button is gone in v4. I presume this means this feature is activated by default, and it will be used whenever you trust some keys (displaying then the checkmark on emails sent to verified addresses). In such a case one should update the ["Learn more" link](https://protonmail.com/support/knowledge-base/address-verification/), since it gives the explanation for the v3 flow.

With the yellow alert we have a bigger problem. It's telling you:

> Address Verification with Trusted Keys is enabled for this address. To be able to send to this address, first trust public keys that can be used for sending.

But there is no button for enabling Trusted Keys now! So this alert, which appears because no trusted key is valid for sending emails, does not make much sense as it is written now. Also, in case Trusted Keys is enabled by default, if there is no key valid for sending that can be trusted (maybe this will never happen for an internal user, but it can happen for users with WKD keys), it seems I would be stuck unable to send emails to such user, since I can't disable Trusted Keys nor I have any valid key to trust.

--------------------------------------------
There are several solutions to this, the easiest and least likely to break things being keeping the v3 flow. But I don't want to implement my own solution. So can anyone update me on how do we want to deal with this exactly in v4?

**Comment by econdepe** [comment]
The second question is simpler. For an external user, the modal looks like:
![image](https://user-images.githubusercontent.com/33841139/65590031-5ec59a00-df8a-11e9-8896-f07548b9eb05.png)

In case I choose PGP/Inline as cryptographic scheme, given that this scheme forces plain text messages, I wonder if we should set the email format to plain text automatically in case the PGP/Inline option is chosen

**Comment by bartbutler** [comment]
IIRC, 'Turning on trusted keys' is defined as having >= 1 trusted keys as you guessed. I don't have any other feedback for your first question, though I always though the v3 flow with the slider was weird (maybe a 'trust all keys' button would make more sense).

For the second option, no, we don't want to set the format to plain text because the mail could have multiple recipients, some with PGP/inline, some with PGP/MIME, some internal, etc. and we don't want to remove HTML formatting for all recipients just because it will be removed for one.

**Comment by econdepe** [comment]
Personally, I also find a bit weird the v3 flow. To me, it makes more sense that the trusted keys feature is "on" by default. Then, whenever some valid (for encryption) public keys are marked as trusted, address verification takes place for emails using these keys. If no valid key is marked as trusted, the emails are sent without any address verification (as it used to be the case). We can show a warning in the modal if among a non-zero number of public keys associated to an email address, you only mark as trusted invalid ones.
However, such a flow for v4 would require at least three changes:
- Change the article in the knowledge base explaining how to use address verification.
- Change the text of the warning in the modal.
- Right now, in the case "trusted keys" is enabled for an email address, but only invalid keys are marked as trusted, the mail app will not allow me to send emails to this address. Instead it will ask me to trust some keys first (it seems to assume there will be such keys, which presumably is the case for internal users, but may not for external users with WKD keys). This behavior should be substituted by maybe simply showing a warning when writing/sending the email. Something like "hey, notice the only keys you trusted for this email address cannot be used for encryption, so the email will be sent unencrypted"
