### ISSUE TITLE
No contacts are imported from certain csv files

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#292]
**Summary:**

There are three sample CSV files that can't be successfuly imported to our v4 contacts app.

The same files work on v3.

You may download them from issue https://proton.atlassian.net/browse/CLIENT-1781. Contact me if you don't have access,

**Example:**

![image](https://user-images.githubusercontent.com/44697797/67866070-aa8ad680-fb28-11e9-8771-0c10d8277701.png)

**Comment by emnproton** [comment]
Noticed we can't import any contact from the `success.csv` file from the JIRA issue.

The csv contact data columns are looking properly formatted, so not sure why it's failing. Please close this ticket if we don't need to support this type of csv contact lists.

**Example:**

![Bv4SXtc9qy](https://user-images.githubusercontent.com/44697797/68745703-736ff700-05f7-11ea-8d38-6138452860ed.gif)

**Comment by econdepe** [comment]
Well, that csv is not greaty formatted because it has an empty header for the last column. The external library (Papa parse) we're using for parsing it is not doing it properly because of that. I added in #333 an extra layer of parsing in the code so that empty headers are skipped (I couldn't find how to do it with Papa parse).
