### ISSUE TITLE
Missing warning when the contact key is expired or revoked

### ISSUE THREAD

**Issue by DeepSpaceHarbor** [ProtonMail/proton-contacts#355]
**Steps to reproduce**
1. Open contact with expired or revoked key
2. Open advanced settings

**Expected behavior**
Notification about expired or revoked key.
This is what we have in v3:
![image](https://user-images.githubusercontent.com/11393457/69966633-1e007900-1517-11ea-8227-a9dcadd431b6.png)

**Current behavior**
This warning is missing. I don't see any mention of expired or revoked key.

**Comment by econdepe** [comment]
This problem only appears for contacts with corrupted vcards, with a KEY field but nothing on it. For contacts with expired keys in the vcard, the warning is displayed in v4.

I would say this behavior was a bug in v3, since no key would be displayed, but you would still get the toggle for encrypt ON (with which key is that supposed to encrypt?!?) and a message referring to "all uploaded keys"
