### ISSUE TITLE
Merge reminder is not responsive

### ISSUE THREAD

**Issue by emnproton** [ProtonMail/proton-contacts#92]
The blue reminder message that appears above the contact list is not responsive and looks broken on small-screen devices.

**Steps to reproduce:**

1. Go to contacts
2. Decrease your browser window in size until you reach the state shown in the screenshot
3. Notice the merge reminder text doesn't properly wrap

**Example:**

![2019-08-08_190830](https://user-images.githubusercontent.com/44697797/62724946-6352e500-ba14-11e9-873c-b672f2dbebdb.jpg)

**Comment by nico3333fr** [comment]
A bunch of followup: actually, the merger reminder has fixed height due to contact list display (script uses inline styles), and it will be not possible to make it responsive using only CSS (and the script also makes complicated to manage zoom if it does not recalculate height).

Suggestion/workaround: put the reminder below 3 boxes on the right, or manage the list in a different way. To discuss with @EpokK and others.

**Comment by matstaz** [comment]
I like @nico3333fr 's approach to relocate this on the right. under the first line that says "you have 122 contacts in your address book"
